version: '2'
services:
  elasticsearch1:
    image: elasticsearch:1.7.6
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    mem_limit: 2g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - $PWD/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - esnet
    privileged: true
  elasticsearch2:
    image: elasticsearch:1.7.6
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    mem_limit: 2g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - $PWD/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
    privileged: true
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    driver: bridge