version: '3'

services:

  elasticsearch:
    image: elasticsearch:1.7.6
    ports:
      - 9200:9200
    networks:
      - elk

  elasticsearch_slave:
    image: elasticsearch:1.7.6
    networks:
      - elk
    depends_on:
      - elasticsearch
    command: elasticsearch --discovery.zen.ping.unicast.hosts=elasticsearch

networks:

  elk:
    driver: bridge